import { normalizeLocation } from "./locations.js";

export const HOTEL_MAP = {
  "Hillside Elegance": "Oia",
  "Kamari Blue Boutique Hotel": "Kamari",
  "Belvedere Suites": "Firostefani",
  "bus station Fira": "Fira",
  "Callia Retreat Suites - Adults Only": "Fira",
  "Akrotiri Castle View": "Akrotiri",
  "Akrotiri Hidden Gem": "Akrotiri",
  "Avant Garde Firostefani": "Firostefani",
  "Avant Garde": "Akrotiri",
  "Santo Wines": "Pyrgos",
  "Andronikos Santorini Hotel": "Imerovigli",
  "Olympic Villas": "Oia",
  "Ocean Bay Suites": "Kamari",
  "Unique Suites": "Imerovigli",
  "Radisson Blu Zaffron Resort": "Kamari",
  "Cresanto Luxury Suites": "Imerovigli",
  "Remezzo Villas": "Imerovigli",
  "Santo Miramare Beach Resort": "Perivolos",
  "Potamida Suites": "Fira",
  "Sail Inn Studios": "Kamari",
  "Agnadema Apartments": "Fira",
  "Chez Sophie": "Kamari",
  "Ifestos Villa": "Fira",
  "Echoes Luxury Suites": "Oia",
  "Elite Luxury Suites": "Oia",
  "Loizos Stylish Residences": "Fira",
  "WHITE": "Kamari",
  "Hotel Santorini": "Fira",
  "Blue Canaves Boutique Villa": "Oia",
  "Acropole Sunrise": "Kamari",
  "Cultural House": "Pyrgos",
  "Maria's Place - Adults Only": "Oia",
  "Petit Palace Suites": "Messaria",
  "Kamari Santorini": "Kamari",
  "Gyros Place": "Perissa",
  "Sunray Lodgings": "Kamari",
  "Central Bus Station Fira": "Fira",
  "Santolia Art Suites": "Oia",
  "Vogue Suites": "Oia",
  "Lotza Studios": "Foinikia",
  "North Wind Luxury Suites": "Oia",
  "Anemomilos": "Oia",
  "Santonero": "Akrotiri",
  "Black Occhio Villa": "Karterados",
  "Ikaros": "Karterados",
  "White Ark": "Fira",
  "Santo Mangata Boutique Hotel": "Perissa",
  "Langas Villas": "Imerovigli",
  "Hotel Acropole Sunrise": "Kamari",
  "Onar Rooms": "Perissa",
  "Caldera Premium Villas": "Oia",
  "Amaryllis Suites Santorini": "Fira",
  "Sea Sound White Katikies": "Perivolos",
  "Secret Gem Suites": "Ammoudi",
  "Amphitheater Cave Houses": "Fira",
  "Anemos View": "Fira",
  "Hotel Porto Perissa": "Perissa",
  "Ambeli Apartments": "Perivolos",
  "Unique Galini Oia - Adults Only": "Oia",
  "Iconic Santorini": "Imerovigli",
  "Transfer service": "Kamari",
  "Costa Grand Santorini": "Kamari",
  "Andromeda Villas": "Imerovigli",
  "Amity Suites - Adults Only": "Fira",
  "Altana Heritage Suites": "Imerovigli",
  "Hippocampus Hotel": "Kamari",
  "VIP Santorini Transfers and Tours": "Oia",
  "Marizan Caves": "Oia",
  "Chelidonia Luxury Suites": "Oia",
  "Finikas Hotel": "Kamari",
  "Charisma Suites": "Oia",
  "Joanna Villas": "Kamari",
  "Levante Beach Hotel": "Kamari",
  "Thiras-Oias": "Oia",
  "Kamares Apartments": "Fira",
  "Vlyhada Μarina": "Vlychada",
  "Athiri Luxury Suites": "Perivolos",
  "Captain John Oia Cave Houses - Sunset": "Oia",
  "Ianthe Apartments": "Oia",
  "Antonia Hotel": "Fira",
  "Santorini Heart - Hotel": "Fira",
  "Luxus VIP Suites": "Oia",
  "Marianna Hotel": "Perissa",
  "Golden Star": "Fira",
  "Avocado": "Imerovigli",
  "Órmos Athiniós": "Port",
  "Perla Nera Suites": "Fira",
  "Villa Solasta": "Akrotiri",
  "Cliff Side Suites": "Firostefani",
  "Villa Rose": "Fira",
  "Afroditi Venus Beach Resort": "Kamari",
  "Agali Houses": "Firostefani",
  "Sunborn Oia Suites": "Foinikia",
  "Voodoo Bar Santorini": "Kamari",
  "The Majestic Hotel": "Fira",
  "Filira Suites": "Perissa",
  "Kamarela Studios": "Kamari",
  "Epar.Od. Firon-Ias": "Foinikia",
  "MAR n MAR CROWN HOTEL-SUITES": "Kamari",
  "Meltemi Village Hotel": "Perissa",
  "Floralia": "Karterados",
  "Hotel Sunshine": "Kamari",
  "Nostos Beach": "Kamari",
  "RK Beach Hotel": "Kamari",
  "Athinios port": "Port",
  "Kaliya Reimagined Food": "Fira",
  "Nova Santorini Luxury Suites": "Pyrgos",
  "Epar.Od. Firon-Ias 260": "Oia",
  "Afroditi Venus Beach Hotel": "Kamari",
  "OUTOPOIA CAVE STUDIOS": "Oia",
  "Dreamland Ηouses": "Oia",
  "Hotel Mohitero": "Kamari",
  "Vitsentzos Suites": "Imerovigli",
  "Moonlight Apartments": "Fira",
  "Terra Verde Oia by K": "Oia",
  "Hafen Santorin": "Port",
  "Santorini Palace": "Fira",
  "Viva Nove Suites": "Kamari",
  "Neo Suites": "Fira",
  "Alyvia Suites": "Oia",
  "Villa Koronios": "Fira",
  "Ira Hotel": "Fira",
  "Bellonias Villas": "Kamari",
  "Zoe Aegeas Traditional houses": "Oia",
  "Sandy's Paradise- Adults Only": "Perissa",
  "Hector Cave House": "Oia",
  "Fira Basement Studios": "Fira",
  "Kalestesia Suites": "Akrotiri",
  "Orizontes Hotel Santorini": "Pyrgos",
  "Cocoon Suites": "Imerovigli",
  "Orama Hotel": "Fira",
  "Limestone": "Fira",
  "Makedonias 5": "Kamari",
  "San Giorgio": "Fira",
  "Caldera Cliff Illusion": "Fira",
  "Santo Mine Oia Suites": "Oia",
  "Studio Mary": "Perissa",
  "Delta Suites": "Oia",
  "Filomare Oia Suites": "Oia",
  "Oia Spirit Boutique Residences": "Oia",
  "Enalion Suites": "Oia",
  "Sun Rocks Boutique Hotel - Caldera View Suites": "Fira",
  "Oia": "Oia",
  "Santorini Port": "Port",
  "Aegean Gold": "Kamari",
  "Hotel Thira": "Fira",
  "Santa Magia": "Kamari",
  "Alta Vista Suites": "Firostefani",
  "Splendour Hotel and Suites": "Firostefani",
  "Blu Rooms Santorini": "Akrotiri",
  "Aqua Luxury Suites by NOMÉE Hospitality Group": "Imerovigli",
  "Cycladic Suites": "Fira",
  "White Pearl Villas": "Oia",
  "Ananda Suites": "Imerovigli",
  "Villa Livadaros": "Karterados",
  "Divelia Hotel": "Perissa",
  "Epar.Od. Mesarias-Archeas Thiras": "Kamari",
  "Meltemi Excelsior Suites": "Perissa",
  "Santorini Rooftop Hot Tub Suite with Panoramic Views": "Akrotiri",
  "Spiliotica Central Apartments": "Fira",
  "Maistrali Prive": "Karterados",
  "Astarte Suites": "Akrotiri",
  "MiCasa": "Oia",
  "El Greco Resort": "Fira",
  "Platia": "Fira",
  "Filomare Suites": "Oia",
  "Fira": "Fira",
  "Dana Villas": "Fira",
  "La Mer Deluxe Hotel": "Fira",
  "Adorno Oia": "Oia",
  "Tzekos Villas": "Fira",
  "Three Domes Oia - an Iconic Collection": "Oia",
  "Altemar Suites": "Fira",
  "Aldea": "Karterados",
  "Adamant Suites": "Fira",
  "Apricus": "Perissa",
  "Kavalari Hotel - Adults Only": "Fira",
  "Villa Dima - Boutique Hotel": "Perissa",
  "Anemoessa Villa": "Foinikia",
  "Ethos Vegan Suites Fira": "Fira",
  "Galaxy Suites": "Imerovigli",
  "Christos Apartments Oia": "Oia",
  "Alexandros mini suites": "Perissa",
  "Aria Lito Mansion": "Fira",
  "Fira Sunrise and Sea View Cave": "Fira",
  "Chelidonia Traditional Villas": "Oia",
  "Artemis Village": "Karterados",
  "Nikki Beach Resort": "Monolithos",
  "Santorini Old Harbor": "Old Port",
  "Anila Suites": "Fira",
  "La Perla Villas and Suites": "Oia",
  "Mandilaria Studios": "Emporio",
  "Hidden Hills": "Messaria",
  "Muses Cycladic Suites": "Oia",
  "Villa Ilios": "Karterados",
  "Olive Leaf Houses": "Firostefani",
  "3 Elements by Stylish Stays": "Oia",
  "Pension George": "Karterados",
  "Canaves Oia Suites": "Oia",
  "Lefkothea Hotel": "Kamari",
  "my life suites": "Fira",
  "Villa Pelekanos": "Karterados",
  "Kýma Perissa": "Perissa",
  "Kalisperis Hotel": "Messaria",
  "Santorini View Hotel": "Akrotiri",
  "Villa Agas": "Karterados",
  "Sweet Pop": "Fira",
  "Santorini Crystal Blue Boutique Hotel": "Kamari",
  "San Antonio - Small Luxury Hotels of the World": "Imerovigli",
  "Alexander's Suites": "Oia",
  "Alesahne Beach Hotel": "Fira",
  "Nano Suites": "Exo Gonia",
  "Maregio Suites": "Oia",
  "Makris Beach Hotel": "Kamari",
  "Villa Eleftheria": "Perivolos",
  "Ferry entre Atenas y Santorini": "Port",
  "Adorno Oia Suites": "Oia",
  "Anatoli Hotel": "Fira",
  "Anastasia Princess Luxury Beach Residence": "Perissa",
  "Mon Signor Adults Only Boutique Hotel - Kamari Santorini": "Kamari",
  "Veggera Hotel": "Perissa",
  "Villa Maria Rooms": "Fira",
  "Makedonias": "Kamari",
  "Aperanto Suites": "Foinikia",
  "Lava Stone": "Ammoudi",
  "3 Caves by Caldera Houses": "Oia",
  "Thira Santorini Port": "Port",
  "Villa Konstantinos": "Perissa",
  "Marcos Rooms": "Oia",
  "Main Street": "Perissa",
  "Aressana Spa Hotel and Suites": "Fira",
  "Nectarios Villa - Studios": "Fira",
  "Blue Dolphins Santorini": "Firostefani",
  "Narkissos Hotel": "Kamari",
  "CAPE 9 Villas": "Akrotiri",
  "The Boathouse Hotel": "Kamari",
  "Mythos": "Pyrgos",
  "SantoNight Luxury Villas": "Messaria",
  "Blue Sea Hotel": "Kamari",
  "Agiou Athanasiou 69": "Fira",
  "Villa Fotini": "Firostefani",
  "Plastiras Rooms": "Fira",
  "Cave Suite Oia": "Oia",
  "Mystique": "Oia",
  "Alexandra Hotel": "Kamari",
  "Proteas Hotel": "Kamari",
  "Holy Cathedral of Saint John the Baptist": "Fira",
  "Apikia Santorini": "Pyrgos",
  "Pelican Hotel": "Fira",
  "Amaya Selection of Villas": "Oia",
  "Aethrio Sunset Village - Oia": "Oia",
  "Grand View - Megalochori Santorini": "Megalochori",
  "The Amethyst Exclusive Suites Oia": "Oia",
  "Tholos Resort": "Imerovigli",
  "Nik. Nomikou": "Oia",
  "Santellini Hotel": "Kamari",
  "ALMA THERA Boutique Hotel": "Perissa",
  "Port de Santorin": "Port",
  "25is Martiou 25": "Fira",
  "Stella Rocca A Mare": "Imerovigli",
  "You and Me Suites Oia": "Oia",
  "Lefteris Traditional Rooms": "Fira",
  "Casa Grande Santorini": "Megalochori",
  "Sun Angelos Oia - Luxury Cave Suites": "Oia",
  "Altemar Suites Santorini": "Fira",
  "Aeon Suites - Adults Only": "Pyrgos",
  "Smaragdi": "Perissa",
  "Santorini Cable Car - Upper Station": "Fira",
  "Fira Deep Blue Suites": "Fira",
  "Santorini Main Square": "Fira",
  "Fanari Vista Suites": "Fira",
  "Rivari Santorini Hotel": "Kamari",
  "Hotel Mylos": "Firostefani",
  "Bus Stop to Fira": "Oia",
  "Volkan on the Rocks": "Firostefani",
  "Smart Fira Stay -Designed Suites": "Fira",
  "Costa Grand Resort": "Kamari",
  "Iliovasilema Suites": "Imerovigli",
  "Villaki Oia": "Oia",
  "Panorama Boutique Hotel": "Fira",
  "Penelope's Ouzeri Pyrgos Santorini": "Pyrgos",
  "Petra Nera": "Perissa",
  "Sky of Thira": "Fira",
  "Caval I": "Fira",
  "Uma Ray Suites": "Fira",
  "Keti Hotel": "Fira",
  "Perissa BeachFront Rooms": "Perissa",
  "Katikies Santorini - Pelagos House - The Leading Hotels Of The World": "Oia",
  "Santorini Mesotopos": "Messaria",
  "Gianna Suites": "Fira",
  "Karidis Hotel": "Kamari",
  "Imerovigli": "Imerovigli",
  "Ptolemeos Hotel": "Fira",
  "Gaia Suites": "Oia",
  "Istoria": "Perissa",
  "Abelonas Village": "Megalochori",
  "Kasimatis by La Perla - Adults Only": "Imerovigli",
  "Finikia Memories Hotel (Finikia's Place)": "Foinikia",
  "Nissia Apartments": "Kamari",
  "Manos Small World": "Fira",
  "Mardanza Krokos Suites": "Imerovigli",
  "Daydream Luxury Suites": "Fira",
  "Hotel Leta": "Fira",
  "Akrorama Villa and Suites": "Akrotiri",
  "Grand View Hotel": "Megalochori",
  "Arapiou Apartments": "Perissa",
  "Kima Oia Suites": "Oia",
  "The Nest Apartments": "Fira",
  "Pano Meria Venetian Style Studio I": "Oia",
  "Santorini Kastelli Resort": "Kamari",
  "Selini Ηotel": "Kamari",
  "Santo Pure Oia Suites": "Oia",
  "Terra Blue Santorini": "Kamari",
  "Anastasia Princess Luxury Beach Residence - Adults Only": "Perissa",
  "Villa Thiranthemis": "Fira",
  "Santo Blue Horizon - The Blue Domes View": "Oia",
  "Hotel Lodos": "Karterados",
  "Chic Hotel Santorini": "Firostefani",
  "Sandy's Paradise Infinity Resort": "Perissa",
  "Vinas Place City Center": "Fira",
  "Anemomilos Hotel Apartments Villas": "Oia",
  "Altera Pars Suites": "Messaria",
  "Philippion Boutique Hotel": "Fira",
  "Amerikanos Villas": "Oia",
  "Anessis": "Fira",
  "Kalisti Hotel & Suites": "Fira",
  "Oia Steps": "Ammoudi",
  "Lackos Luxury Suites": "Vourvoulos",
  "Arlene Suites": "Messaria",
  "Panorama Oia Apartments": "Foinikia",
  "Hotel Golden Star": "Fira",
  "Santorini Heart Hotel": "Fira",
  "The Museum Project Oia": "Oia",
  "Folia Apartments": "Fira",
  "The Vasilicos": "Imerovigli",
  "Fira Heart Studios": "Fira",
  "Ducato di Oia - Adults Only": "Oia",
  "Santorini Theasis Suites": "Imerovigli",
  "Delfini Villas": "Oia",
  "Hotel Perissa": "Emporio",
  "Cally Cave House": "Fira",
  "Aressana Spa Hotel": "Fira",
  "Absolute Bliss": "Imerovigli",
  "Aegean Plaza Hotel": "Kamari",
  "Meroviglia Boutique Hotel": "Imerovigli",
  "Meltemi Village": "Perissa",
  "Dioskouri Art Villas": "Kamari",
  "Tholaki luxury home": "Kamari",
  "Bluedome Cavehouses by Otium Villas": "Oia",
  "Kamari Beach Hotel": "Kamari",
  "Ilioperato Hotel": "Imerovigli",
  "Afroessa Hotel by Caldera Houses": "Imerovigli",
  "Oia Mare Villas": "Oia",
  "Caldera's Bliss Suites": "Fira",
  "Aqua Blue Beach Hotel": "Perissa",
  "Impressive One Hotel": "Fira",
  "King's Suites": "Kamari",
  "Alleys All-Suite Hotel": "Pyrgos",
  "Regina Mare-Adults Only Hotel": "Imerovigli",
  "Cosmopolitan Suites - Small Luxury Hotels of the World": "Fira",
  "Senses Boutique Hotel": "Imerovigli",
  "Senses Suites": "Imerovigli",
  "Akis Hotel": "Kamari",
  "Alaxandross mini suites": "Perissa",
  "WeSense Santorini by Caldera Houses": "Imerovigli",
  "Megalochori": "Megalochori",
  "Iliovasilema Hotel": "Imerovigli",
  "Ark": "Pyrgos",
  "Skyfall Suites - Adults Only": "Pyrgos",
  "Meltemi Blu - Adults Only": "Perissa",
  "Cleo's Dream Villa": "Oia",
  "Petri Suites": "Perivolos",
  "Casa Frati Suites": "Perivolos",
  "Porto Fira Suites": "Fira",
  "Lilium Hotel Santorini": "Messaria",
  "Zephyros Hotel": "Kamari",
  "Nastram Suites Oia": "Oia",
  "Galatia Villas": "Fira",
  "Kapari Natural Resort": "Imerovigli",
  "Santorini Sun Villas": "Oia",
  "Perissa": "Perissa",
  "Valery Suites": "Fira",
  "Aura Marina Apartments Santorini": "Akrotiri",
  "Tiara Suites Fira - Cycladic": "Fira",
  "25is Martiou 405": "Fira",
  "Elysian Santorini": "Foinikia",
  "Elixir Del Mar on the Beach": "Kamari",
  "Mardanza House": "Imerovigli",
  "Blue Sea": "Kamari",
  "HIDEAWAY CAVE HOUSE": "Oia",
  "Agnadi View Villa": "Foinikia",
  "Kiklamino Sunset Suites": "Foinikia",
  "Bligos Villas": "Oia",
  "Glykeria Mini Suites": "Perivolos",
  "Asha Luxury Suites": "Fira",
  "SPIROS": "Perissa",
  "Divino Caldera": "Akrotiri",
  "Aeolos Art": "Imerovigli",
  "White Element": "Messaria",
  "Theodora Suites": "Oia",
  "Wisteria Apartments": "Karterados",
  "Mitropoleos": "Fira",
  "Theoxenia Caldera Hotel": "Fira",
  "Atrium Villa": "Fira",
  "Veranda View": "Imerovigli",
  "Sunflower ApartHotel": "Kamari",
  "Athermi Suites - Adults Only": "Megalochori",
  "Kykladonisia Traditional Settlement": "Fira",
  "Calypso Heaven": "Messaria",
  "Hotel Matina": "Kamari",
  "Unique Leta": "Fira",
  "Porto di Santorini": "Port",
  "Alkyon Hotel": "Kamari",
  "White Pearl Laokasti Suites": "Oia",
  "Asma Suites": "Fira",
  "Smaro Studios": "Firostefani",
  "Lolita's Gelato": "Oia",
  "Red Beach Viewpoint": "Akrotiri",
  "Strogili Hotel - Adults Only": "Kamari",
  "Picturesque Blue Dome Santorini": "Oia",
  "Church of the Holy Cross": "Perissa",
  "Sorocada Private House": "Akrotiri",
  "Corner Food": "Perissa",
  "Asimina Hotel": "Fira",
  "Pension Ptolemeos": "Fira",
  "Firostefani": "Firostefani",
  "Aroma Suites": "Fira",
  "BlackBeach Village": "Perissa",
  "Centro Fira": "Fira",
  "Hotel Thirasia": "Fira",
  "Erato Apartments": "Firostefani",
  "Kivotos Santorini": "Imerovigli",
  "Three Bells Suites": "Firostefani",
  "Nova Luxury Suites": "Pyrgos",
  "Fileria Suites": "Oia",
  "Opalia Suites": "Perissa",
  "NĒRO Suites by NOMÉE Hospitality Group": "Imerovigli",
  "Gabbiano Traditional Cave Houses": "Fira",
  "Aeolos Studios": "Imerovigli",
  "Astra Suites": "Imerovigli",
  "Mon Signor": "Kamari",
  "Lavadoze Luxury Suites": "Exo Gonia",
  "Dekigala 40c": "Fira",
  "Hotel Babis": "Karterados",
  "Blue Waves Suites": "Kamari",
  "Rocabella Santorini Hotel": "Imerovigli",
  "Monolithia": "Monolithos",
  "Kivotos Santorini - Preferred Hotels": "Imerovigli",
  "Canaves Oia Suites - Small Luxury Hotels of the World": "Oia",
  "Vallais Villa": "Imerovigli",
  "Thousand Stars Suites": "Kamari",
  "Villa Toula": "Fira",
  "Amer Suites": "Fira",
  "Katerina Kafieri Apartments": "Fira",
  "Aria Suites": "Fira",
  "Aura Suites": "Fira",
  "Perivolos Apartments": "Emporio",
  "Casa Sigala volcano": "Oia",
  "Sandblu Santorini": "Kamari",
  "Old Castle Oia": "Oia",
  "Sakas Residences": "Karterados",
  "Central Fira Suites": "Fira",
  "Anchor Suites": "Foinikia",
  "Thea Apartments": "Imerovigli",
  "Efippos-Santorini Riding Center": "Vlychada",
  "On the Cliff": "Fira",
  "IfestAu.4 Suites": "Fira",
  "City Center Suites": "Fira",
  "La Maltese Estate": "Imerovigli",
  "M Residence Santorini Conelia Cave": "Fira",
  "NĒRO Boutique Hotel": "Imerovigli",
  "Casa Sigala arch": "Oia",
  "Sole d'oro Luxury Suites": "Oia",
  "Asterolithos": "Fira",
  "Avianto Suites": "Imerovigli",
  "Hotel Hellas": "Fira",
  "Aroma Azalea studios": "Kamari",
  "Nostos Central Cave House with jacuzzi": "Fira",
  "Cuore Santo Suites": "Fira",
  "Hill Suites": "Fira",
  "May Seven Suites": "Megalochori",
  "White Harmony Suites": "Megalochori",
  "Roula Villa Studios": "Perissa",
  "Villa Anto": "Fira",
  "Heliophos Boutique Caves": "Foinikia",
  "Apollo Rooms": "Perissa",
  "hom Santorini": "Oia",
  "Anemomilos Villa": "Fira",
  "Veggera Beach Hotel": "Perissa",
  "Porto de Santorini": "Port",
  "Altea Apartments": "Fira",
  "Harmony Suites": "Fira",
  "Splendour Hotel": "Firostefani",
  "Santorini Camping": "Fira",
  "Hotel The Best": "Perissa",
  "Boutique 88 Fira": "Fira",
  "Nostos Apartments": "Oia",
  "Revelis Villa": "Fira",
  "Dilay Cafe Snack Bar": "Kamari",
  "Akra Suites": "Imerovigli",
  "Villa Manos Hotel": "Karterados",
  "Amera Suites": "Fira",
  "Deluxe Suites Santorini": "Fira",
  "Galini": "Foinikia",
  "Hyperion Oia Suites": "Oia",
  "Anteliz Suites": "Fira",
  "Aspaki Exclusive Hotel by Art Maisons": "Oia",
  "Stella Nomikou Apartments": "Fira",
  "Babis Hotel": "Karterados",
  "Dream Island Hotel": "Fira",
  "Sophia Luxury Suites": "Imerovigli",
  "Sweet Heart Studios": "Kamari",
  "HOTEL Dolphin": "Perissa",
  "Sophia Boutique Hotel": "Foinikia",
  "White Cellar cave houses by Cycladica": "Oia",
  "Pearl Inn Hotel by Pearl Hotel Collection": "Imerovigli",
  "City Break": "Fira",
  "Taverna El Greco": "Fira",
  "Castle of Oia": "Oia",
  "Coconut Residence": "Karterados",
  "Villa Thiranthemis Santorini": "Fira",
  "Brilliance Suites": "Imerovigli",
  "Villa Margarita": "Karterados",
  "Santopaz Suites": "Oia",
  "Kamares Neoklassiko": "Fira",
  "Aeifos Boutique Hotel": "Imerovigli",
  "Divino Suites": "Fira",
  "Aegean Blue Suites": "Pyrgos",
  "Sagma Beach Rooms": "Perissa",
  "Villa Kisiris": "Imerovigli",
  "haven van Santorini": "Port",
  "Notos Therme and Spa by Mr and Mrs White": "Vlychada",
  "Irene City Villas": "Fira",
  "Pura Vida Cave House": "Imerovigli",
  "KooKoo Bar Restaurant Sunset Rooftop": "Oia",
  "Finikia 847 02": "Foinikia",
  "SunUp Lux Villa": "Oia",
  "Villa Murano": "Fira",
  "Hom Santorini": "Oia",
  "Aelia Luxury Suites": "Karterados",
  "OIA UNIQUE HOMES by K": "Oia",
  "Marousi Rooms": "Perissa",
  "Agiou Athanasiou 39": "Fira",
  "Villa Happening": "Imerovigli",
  "Aghios Artemios Traditional Houses": "Imerovigli",
  "Golden Moments Luxury Stone Villas C": "Messaria",
  "Aspa Villas": "Oia",
  "Porto Castello": "Fira",
  "Markakis Studios Fira Town": "Fira",
  "Oia Parking": "Oia",
  "Afrodete Hotel": "Fira",
  "De Sol Hotel": "Fira",
  "Alloro Perissa": "Perissa",
  "Ikio Concept": "Pyrgos",
  "New Haroula": "Fira",
  "Artemis Suites": "Megalochori",
  "Sweet Home": "Karterados",
  "Heyday Luxury Suites": "Perissa",
  "Rooms By Lignou": "Fira",
  "Elessa Hotel": "Pyrgos",
  "Ambience Suites": "Fira",
  "Agave Santorini Design Βoutique Hotel": "Imerovigli",
  "Nefeli Homes - Adults Only": "Imerovigli",
  "The lemon tree studio": "Fira",
  "Cooper's Cave house with heated Jacuzzi": "Megalochori",
  "Casa Sigala sunset": "Oia",
  "Ikio Concept Santorini": "Pyrgos",
  "Caldera Romantica Hotel": "Akrotiri",
  "Aigialos Luxury Traditional Settlement": "Fira",
  "Hotel Kallisto": "Imerovigli",
  "The Arches": "Oia",
  "Reverie Santorini Hotel": "Firostefani",
  "Mythical Blue Luxury Suites": "Fira",
  "Kalimera Hotel": "Akrotiri",
  "Fanari Villas": "Oia",
  "North Santorini - A Luxury Spa Hotel": "Pyrgos",
  "Little Rock Villa - Oia": "Oia",
  "Old Castle Oia by Mr and Mrs White": "Oia",
  "Santa Mar ECO Suites": "Karterados",
  "Fira Cozy Rooms": "Fira",
  "Alonia Studios": "Firostefani",
  "Oscar Hotel": "Kamari",
  "Caval II": "Fira",
  "La Torretta Suites": "Pyrgos",
  "Villa Soula": "Fira",
  "Nefeles Luxury Suites": "Fira",
  "Amerisa Suites": "Fira",
  "Orthodox Metropolitan Cathedral": "Fira",
  "Kamari Beach": "Kamari",
  "Epavlis Hotel": "Kamari",
  "Hotiday Santorini Oia": "Foinikia",
  "Enarma Suites": "Megalochori",
  "Oia Treasures Art Suites": "Oia",
  "Maiandros Suites": "Karterados",
  "Diamond on the cliff Hotel": "Imerovigli",
  "Myst Boutique Hotel": "Oia",
  "Volcano View Hotel Santorini": "Fira",
  "Safrani Suites": "Fira",
  "Safrani Suites": "Fira",
  "June Twenty Suites": "Messaria",
  "La Bellezza Eco Boutique Hotel": "Kamari",
  "Acqua Vatos Santorini Hotel": "Kamari",
  "Fira Deep Blue Suites": "Fira",
  "Abasa Suites": "Fira",
  "Athina Luxury Suites": "Fira",
  "Villa Maina": "Kamari",
  "Pink Sophia Maria": "Imerovigli",
  "White": "Imerovigli",
  "Aja Retreat Luxury Suites": "Kamari",
  "Ifestia Hotel": "Kamari",
  "Onyx Hotel": "Karterados",
  "Vallas Apartments": "Firostefani",
  "PERIVOLAS MARKET": "Oia",
  "Elea Resort - Adults Only": "Oia",
  "Anthonas Apartments": "Imerovigli", 
  "Evgenia Villas": "Fira",
  "Voca Hotel": "Kamari",
  "Kastro Suites": "Fira",
  "Marillia Village": "Perivolos",
  "Hotel Bella Santorini": "Perivolos",
  "Smarula Villa": "Firostefani",
  "IKIES Santorini": "Oia",
  "Pezoules of Oia": "Oia",
  "Orabel Suites Santorini (Adults Only)": "Perivolos",
  "Villa Amore": "Karterados",
  "OPALIA SUITES": "Perissa",
  "Canaves Ena - Small Luxury Hotels of the World": "Oia",
  "Atlantis Beach Villa": "Perivolos",
  "MIA'S RESTAURANT SANTORINI": "Oia",
  "Serenità Luxury Suites": "Akrotiri",
  "Palm Studios": "Perissa",
  "Chroma Suites": "Oia",
  "Alizea Villas": "Fira",
  "Emfasis Luxury Villa with heated Jacuzzi-Sunset view": "Fira",
  "Seaside by Manos": "Kamari",
  "Dioskouri art Villas": "Kamari",
  "Olia Villas": "Imerovigli",
  "Petros Villa": "Fira",
  "Spitia Santorini Villa Collection": "Oia",
  "Oasis Suites Fira": "Fira",
  "Rose Bay Hotel": "Kamari",
  "Fanari Villas Santorini": "Oia",
  "MG Boutique Hotel": "Perissa",
  "Oia VineyART Homes": "Oia",
  "Nevma Suites": "Firostefani",
  "Callia Retreat Suites": "Fira",
  "Kasteli Luxury Rooms": "Perissa",
  "Thirea Suites": "Oia",
  "Evilio Houses": "Oia",
  "Santorini Villatzio Suites": "Messaria",
  "Astir Thira Hotel": "Fira",
  "Amelot Art Suites": "Fira",
  "Iriana Suites": "Fira",
  "Griseo Villas": "Karterados",
  "McDonald's Σαντορίνη": "Fira",
  "Black Diamond Suites": "Akrotiri",
  "Apeiron Blue Santorini - Sustainable Adults Only 14 Plus": "Fira",
  "Kalya Suites": "Kamari",
  "Nissos Thira Hotel": "Fira",
  "Santa Elena": "Kamari",
  "Maison Dalidaz": "Messaria",
  "Nissia Beach Apartments": "Kamari",
  "Blue Bay Villas": "Kamari",
  "Villa Valvis": "Perissa",
  "Allure Breeze Suites": "Oia",
  "Holy Church of Saint Gerasimos": "Fira",
  "Danae Villa": "Fira",
  "Oia Sunset Villas": "Oia",
  "Seven Grapes - Karterados": "Karterados",
  "Blessed Blue Boutique Cave Suite": "Oia",
  "Cyclops Beach Apartments": "Perivolos",
  "Strogili": "Oia",
  "Carlos Pension": "Akrotiri",
  "Zoodochou Pigis": "Kamari",
  "Polydefkis Hotel": "Kamari",
  "Andronis Arcadia Hotel": "Oia",
  "Barolo Restaurant": "Fira",
  "Raeti Fira Residence": "Fira",
  "Volcano View by Caldera Collection": "Fira",
  "Dreaming View Suites": "Imerovigli",
  "Paradise Resort": "Akrotiri",
  "East Wind Perissa": "Perissa",
  "Vinebranch Villa": "Vourvoula",
  "Santorini Airport (JTR)": "Airport",
  "Villa Valvis Hotel": "Perissa",
  "Puerto de Santorini": "Port",
  "Blue Dolphins Apartments": "Firostefani",
  "Acroterra Rosa Luxury Suites": "Akrotiri",
  "Aethra Vegan Caves": "Pyrgos",
  "Armeni Village": "Oia",
  "Dolphins Apartments": "Firostefani",
  "Seajets": "Port",
  "Karpimo North - Boutique Suite with Sunset View": "Pyrgos",
  "Island Charm Imerovigli": "Imerovigli",
  "Kelenis Apartments": "Karterados",
  "Elements Cave Suites": "Megalochori",
  "Bedspot Hostel": "Fira",
  "Nikos Hotel": "Karterados",
  "Bus Stop Imerovigli": "Imerovigli",
  "Marvarit Suites": "Messarua",
  "Pension St.George Rooms": "Perivolos",
  "Eparchiaki Odos Ormou Athiniou": "Port",
  "Klοstrá Hotel": "Oia",
  "Santo Miramare Resort Perivolos": "Perivolos",
  "Villa Pavlina": "Karterados",
  "Phaos 1870": "Pyrgos",
  "White Santorini": "Imerovigli",
  "Dimitris Restaurant - wedding venue - greek nights": "Kamari",
  "Steki souvlaki": "Steki souvlaki",
  "Whitedeck Santorini": "Imerovigli",
  "Rimida Villas": "Oia",
  "Enalion White Suites Oia": "Oia",
  "Oia's Cellars": "Oia",
  "Tarelis Beach Apartments": "Kamari",
  "Annio Santorini": "Imerovigli",
  "Leonidas Apartments": "Kamari",
  "GTK Santorini Oia Sunset Villas": "Oia",
  "Imerti Suites": "Oia",
  "Santorini Wine Museum": "Messaria",
  "Villa Santorini Serenity with private Pool": "Monolithos",
  "Petuna Cave Suites": "Fira",
  "Edem Boutique Suites": "Foinikia",
  "Santo Mangata Boutique Hotel and Spa": "Perissa",
  "La Belle Vie - Santorini - Adults Only": "Kamari",
  "Loukas": "Perissa",
  "Arvanitis Market Akrotiri": "Akrotiri",
  "Danae Suites Santorini": "Foinikia",
  "Akrotiri Hotel": "Akrotiri",
  "Dionysos Street": "Kamari",
  "Aloia Villas": "Oia",
  "Caldera's Memories": "Imerovigli",
  "Atlantida Spacious Flat": "Fira",
  "Studios Marios": "Kamari",
  "Thermes Luxury Villas by Mr and Mrs White": "Megalochori",
  "Oia Suites": "Oia",
  "Edem Boutique Suites": "Foinikia",
  "Niabelon Suites - Private Jacuzzi Sunset View": "Oia",
  "Smy Santorini Suites": "Pyrgos",
  "BeSanto Imerovigli": "Imerovigli",
  "Suite Home Santorini": "Fira",
  "White Side Suites": "Oia",
  "Fira Pulse Designed Suites": "Fira",
  "Villa Aegeon": "Megalochori",
  "Villa Dina with private Juccuzi": "Perissa",
  "Wet Stories Santorini": "Perivolos",
  "myLithos Suites": "Monolithos",
  "N RENIERIS Apartments": "Firostefani",
  "Aplai Dome": "Oia",
  "Pegasus Suites": "Imerovigli",
  "Λιμάνι Σαντορίνης": "Port",
  "Rare Meat Restaurant Santorini": "Imerovigli",
  "Meli Meli": "Imerovigli",
  "Nik. Nomikou 11": "Oia",
  "Santana Apartments": "Perivolos",
  "AMĀRIA Beach Resort": "Monolithos",
  "Candele Suites": "Fira",
  "Aerino Villa": "Firostefani",
  "Zen Villas": "Akrotiri",
  "BeSanto Imerovigli": "Imerovigli",
  "Altana Cliffside Villas": "Imerovigli",
  "Oldtown Suites Fira": "Fira",
  "Villa Aegeon": "Megalochori",
  "Pina Caldera Residence": "Oia",
  "Above Blue Suites": "Imerovigli",
  "Mnimes Guesthouses": "Firostefani",
  "The Cliff Reflections - Adults Only": "Megalochori",
  "Residence Resorts Road": "Oia",
  "Zannos Melathron by Omilos Hotels": "Pyrgos",
  "Horizon Resort": "Kamari",
  "The Cosmopolitan - Karterados Urban Suites": "Karterados",
  "Epic View Suites": "Akrotiri",
  "Tui Blue Meltemi": "Perissa",
  "Hotel Sunrise": "Fira",
  "Lithos Cave": "Foinikia",
  "Noème Santorini": "Perissa",
  "Artia Mansion": "Oia",
  "Piccole Case": "Kamari",
  "Kastro Oia Houses": "Oia",
  "White Lily Suites": "Perivolos",
  "Emerald Collection Suites": "Karterados",
  "Illusion Suites": "Fira",
  "Kokkinos Villas": "Akrotiri",
  "Ipapantis 10": "Fira",
  "Villa Roussa City Center": "Fira",
  "Loft Kaves Pool": "Pyrgos",
  "palmariva-villas": "Fira",
  "Galaria Serenity Suites": "Messaria",
  "Athermi Suites": "Megalochori",
  "Colombo's Beachfront": "Foinikia",
  "Mr": "Foinikia",
  "Noelia Suites by MPS": "Oia",
  "Edem Boutique Hotel": "Foinikia",
  "Costa Marina Villas": "Fira",
  "White Dream Suites": "Fira",
  "Παναγία Κόκκινη 2": "Karterados",
  "Anamnesis City Spa": "Fira",
  "IRIDA Santorini": "Imerovigli",
  "Brusco": "Pyrgos",
  "Alunia Incognito Suites - Adults Only": "Pyrgos",
  "Studios Apartments Kapetanios": "Perissa",
  "Fusionnelle": "Fira",
  "ΔΗΜΗΤΡΑΣ": "Kamari",
  "Moto Chris": "Fira",
  "DL Santorini": "Monolithos",
  "Domus Pyrgos": "Pyrgos",
  "Goulielmos Hotel": "Akrotiri",
  "Katris Apartments": "Fira",
  "Melina Hotel": "Fira",
  "Anna's": "Karterados",
  "Dimitris Villa": "Kamari",
  "Golden Star Ξενοδοχείο": "Fira",
  "Tiara Suites Fira - Cycladic": "Fira",
  "Anatelo house": "Fira",
  "Sellada Beach": "Perissa",
  "Kafieris View": "Firostefani",
  "Melitini": "Oia",
  "Erice Fira by EasyStay": "Fira",
  "Caldera View Resort - Adults Only": "Akrotiri",
  "Nano Oia Canaves": "Oia",
  "Iris Boutique Hotel": "Kamari",
  "The Best": "Perissa",
  "Sea Wave Villa": "Perissa",
  "Perissa Bay Bar": "Perissa",
  "Soil of Sun Luxury Villas": "Megalochori",
  "Pueblo viejo boutique house": "Kamari",
  "On The Rocks": "Imerovigli",
  "Vassaltis Vineyards": "Vourvoulos",
  "Sunset Paradise Oia": "Foinikia",
  "Sea Breeze Santorini Beach Resort": "Perivolos",
  "Μεγ. Αλεξάνδρου": "Kamari",
  "Kalisti Hotel": "Fira",
  "Bonsai Luxury Suites": "Karterados",
  "Sunset Nama Suites": "Oia",
  "Παναγίας Μυρτιδιωτίσσης": "Kamari",
  "Main Street": "Fira",
  "Mr and Mrs White Oia - Santorini": "Foinikia",
  "Luno Santorini Oia": "Oia",
  "PUBLIC PARKING OIA": "Oia",
  "Gallis Supermarket": "Imerovigli",
  "You and Me Suites": "Firostefani",
  "Fava Eco Suites": "Foinikia",
  "Eternity Suites Santorini": "Fira",
  "Aqua Cozy Suites": "Perissa",
  "Nest": "Perissa",
  "Feggari Apartments": "Firostefani",
  "Finikas Santorini": "Kamari",
  "In the heart of Fira": "Fira",
  "Terra Verde Oia Suites": "Oia",
  "Apeiron Perissa": "Perissa",
  "Above Bistro": "Imerovigli",
  "El Verano Suites": "Imerovigli",
  "Firaxenia rooms": "Fira",
  "Lioyerma Cave Villa": "Oia",
  "Arvanitis Cave Village": "Akrotiri",
  "Elkaza Villas": "Fira",
  "Anna Maria Rooms Santorini": "Perissa",
  "Sweet pop": "Fira",
  "Luno Santorini Oia": "Oia",
  "Anna Maria Rooms Santorini": "Perissa",
  "ILIADA-ODYSSEAS RESORT": "Perivolos",
  "Sagma Central Rooms with Pool": "Perissa",
  "Andronis Boutique Hotel": "Oia",
  "Elysian Retreat": "Oia",
  "Enjoy Villas": "Kamari",
  "Elements of Caldera Suites": "Akrotiri",
  "Delfini Villas Hotel Santorini": "Oia",
  "La Ponta Villas": "Akrotiri",
  "Nelya Suites": "Megalochori",
  "Cavo Tagoo Santorini": "Imerovigli",
  "DEILINO Food Drink": "Oia",
  "Villa Anemomilos Perissa": "Perissa",  
  "White wave studios": "Kamari",
  "Sensia Luxury Apartment with Hot tub": "Oia",
  "HOTEL MOHITERO": "Kamari",
  "Lilium Homes": "Karterados",
  "Post Office": "Oia",
  "Villa Stella": "Fira",
  "Memories Beach Hotel": "Monolithos",
  "Villa Kalamia Dolphins": "Perissa",
  "Sleep with Me- Fira Center": "Fira",
  "UMA RAY SUITES": "Fira",
  "Alegria suites by casa Sigala": "Oia",
  "Villa Galinia": "Akrotiri",
  "Atlantis Hotel": "Fira",
  "Preka Maria": "Kamari",
  "Tristhenia": "Perissa",
  "Gold Suites - Small Luxury Hotels of the World": "Imerovigli",
  "AquaLung Suites": "Kamari",
  "Nostos Apartments Kamari": "Kamari",
  "My life suites": "Fira",
  "Maryloujohn Villas Oia": "Oia",
  "Glaros Hotel": "Kamari",
  "Marina's Studios": "Perivolos",
  "Andronikos Canaves": "Oia",
  "Aegeeis": "Perissa",
  "SeaVibe - Restaurant": "Kamari",
  "Aeolos Eco Studios": "Imerovigli",
  "Fanouris Condo - Adults Only - Traditional Apartment by Cocomat": "Kamari",
  "Villa Ilias": "Firostefani",
  "The Tree Houses Santorini": "Emporio",
  "White Curves Santorini": "Akrotiri",
  "Morfi Cave House": "Oia",
  "CUORE SANTO SUITES": "Fira",
  "Agapi Villas": "Karterados",
  "Armenaki": "Oia",
  "PetrAn": "Fira",
  "Hotel Star Santorini": "Megalochori",
  "Arco Bianco Suites": "Akrotiri",
  "Ammos Oia Mansion": "Oia",
  "Aenaon Blue": "Kamari",
  "Dimitris Studios": "Perissa",
  "Sun Springs Suites": "Kamari",
  "Aethera Apartments": "Megalochori",
  "Elitoz Suites": "Oia",
  "Orfeas Apartments": "Kamari",
  "Holiday Beach Resort Santorini": "Perivolos",
  "Apeiron Blue Santorini - Adults Only 14 plus - Apeiron Hotels": "Messaria",
  "The Mill Haven Santorini": "Oia",
  "Armeni Luxury Villas": "Oia",
  "Casa paradiso private villas": "Oia",
  "Xaravgi Resort Suites": "Fira",
  "Canaves Sunday": "Oia",
  "Coastal Escape - 2 min from Perissa Beach": "Perissa",
  "Hotel Santa Elena": "Kamari",
  "Paradise Resort Santorini": "Akrotiri",
  "Cavo Bianco Boutique Hotel": "Kamari",
  "Villa Maria Apartments": "Akrotiri",
  "Epar.Od. Firon-Ias 1": "Oia",
  "Maison Des Lys - Luxury Suites": "Akrotiri",
  "Παναγίας Μυρτιδιωτίσσης 2": "Kamari",
  "Santorini Camping/Rooms": "Fira",
  "Hotel Mathios": "Akrotiri",
  "Lucia Villas": "Perissa",
  "Saint Santorini": "Oia",
  "Thirea Studios": "Oia",
  "Sofia Firostefani": "Firostefani",
  "Aether Canava - Heated Pool in the heart of Fira": "Fira",
  "AetherOia Suites": "Oia",
  "CUORE SANTO SUITES": "Fira",
  "Castro Hotel": "Kamari",
  "Aigaion Irish Pub": "Kamari",
  "Honeymoon Petra Villas": "Imerovigli",
  "Ersi Villas": "Firostefani",
  "Sun Springs Suites": "Kamari",
  "Canaves Epitome": "Oia",
  "Philoxenia Hotel": "Perissa",
  "Oia to Fira Hike (Start)": "Oia",
  "Agiou Athanasiou 2": "Fira",
  "Dilino": "Kamari",
  "Apeiron Perissa - Apeiron Hotels": "Perissa",
  "ThoÃ¨ Oia Suites": "Oia",
  "Daedalus Hotel": "Fira",
  "Tamarix Del Mar Suites": "Kamari",
  "Agapi Villas": "Karterados",
  "Fourni Bakery": "Oia",
  "AquaLung Suites": "Kamari",
  "Airth Santorini Suites": "Fira",
  "Nostos Suites Kamari": "Kamari",
  "Eteoro Suites": "Imerovigli",
  "Villa Michalis": "Vlychada",
  "Lithora Suites Santorini": "Oia",
  "Βασ. Φιλίππου": "Kamari",
  "Makarios Hotel": "Kamari",
  "Ifestio Villas Santorini": "Oia",
  "Nik. Nomikou 1": "Oia",
  "Andronikos Santorini": "Imerovigli",
  "Rody Caves Oia": "Foinikia",
  "Apanemo Hotel": "Akrotiri",
  "Atrina Canava 1894": "Oia",
  "Annouso Villa by Caldera Houses": "Oia",
  "On The Rocks - Small Luxury Hotels of the World": "Imerovigli",
  "Aqua Blue Hotel": "Perissa",
  "BlackBeach village": "Perissa",
  "Sophia Oia View": "Oia",
  "Mill Houses New Elegant Suites by Mr and Mrs White": "Firostefani",
  "Agave Santorini Design Boutique Hotel": "Imerovigli",
  "Sun Rocks Boutique Hotel": "Firostefani",
  "Gold Suites - Small Luxury Hotels of the World": "Imerovigli",
  "Smy Mediterranean White Santorini": "Monolithos",
  "Armonia": "Kamari",
  "Holiday Beach Resort Santorini": "Perivolos",
  "Abrazo Villas": "Imerovigli",
  "Stavros Villas": "Karterados",
  "Villa Dioni": "Kamari",
  "Alaso Design Suites": "Fira",
  "Neema Maison Finikia Santorini": "",
  "Finikia - Oia": "Foinikia",
  "Vothonas 847 00": "Messaria",
  "Sleep with Me- Fira Center": "Fira",
  "Acro Caldo Suites": "Akrotiri",
  "Ducato Dream Santorini": "Emporio",
  "Luggage Storage Kamari Village - Radical Storage": "Kamari",
  "Oia to Fira Hike (Start)": "Oia",
  "Rodakas Hotel": "Akrotiri",
  "La Madeleine Oia": "Oia",
  "Argiris Studios": "Kamari",
  "Volcan Secret Cave": "Karterados",
  "Villa Firostefani": "Firostefani",
  "Porto Villa": "Vlychada",
  "Hotel Orizontes Santorini": "Pyrgos",
  "George": "Messaria",
  "ThoÃ¨ Oia Suites": "Oia",
  "Nefeli Traditional Cave Houses": "Messaria",
  "Astro Palace Hotel": "Fira",
  "270 Oias View": "Oia",
  "9FJM 3W": "Kamari",
  "9FHC+MW": "Fira",
  "Dragonfly Villas": "Kamari",
  "Avant Garde Suites": "Akrotiri",
  "Ermis 2": "Kamari",
  "Atlas Pension": "Karterados",
  "Παναγίας Μυρτιδιωτίσσης 2": "Kamari",
  "On The Rocks - Small Luxury Hotels of the World": "Imerovigli",
  "Apanemo Hotel": "Akrotiri",
  "Thoè Oia Suites": "Oia",
  "Mill Houses New Elegant Suites by Mr and Mrs White": "Firostefani",
  "Ambition Suites": "Oia",
  "Anemos Cave Suites": "Imerovigli",
  "UtopOia Apartment": "Oia",
  "Kaleidoscope Oia Suites": "Oia",
  "My Little": "Akrotiri",
  "Villa Basilica Tefsia": "Emporio",
  "Villa Michalis": "Vlychada",
  "Studios Irineos": "Perissa",
  "Alexander Villas": "Imerovigli",
  "Ico Santorini": "Pyrgos",
  "Pearl of Caldera Oia - Boutique Hotel by Pearl Hotel Collection": "Oia",
  "Blue Sapphire Hotel": "Perissa",
  "Gazelle Living": "Imerovigli",
  "Theodora suites": "Oia",
  "DIAMOND on the cliff Hotel": "Imerovigli",
  "9FGH+FG": "Kamari",
  "Thea Cave Villa - Heated Infinity Pool": "Oia",
  "Armenaki": "Oia",
  "Albatros Hotel": "Karterados",
  "Aqua Blue Hotel": "Perissa",
  "Spiridoula Villa - Santorini Seaside Retreats": "Perissa",
  "Aerial Apartments": "Karterados",
  "Hotel Santa Elena": "Kamari",
  "Neema Maison Finikia Santorini": "Foinikia",
  "Noir Santorini": "Monolithos",
  "Antinea Suites Hotel": "Kamari",
  "Domes Novos Santorini": "Oia",
  "Tamarix Del Mar Suites": "Kamari",
  "Caldera's Elements": "Megalochori",
  "Eparchiaki Odos Firon-Ias": "Imerovigli",
  "Sellada Apartments": "Kamari",
  "Villa Kirina Private Traditional House": "Kamari",
  "Anemone Luxury Suites": "Fira",
  "White Concept Caves": "Fira",
  "Top Oia Apartments": "Oia",
  "Christina Pension": "Karterados",
  "Ducato Di Oia": "Oia",
  "Desiterra Resort": "Fira",
  "Top Oia Apartments": "Oia",
  "Aretousa Villas": "Perissa",
  "Ducato Dream Santorini": "Emporio",
  "Opsis Cave House": "Oia",
  "Cavo Bianco": "Kamari",
  "Acanthus Oia - Suites With Outdoor Hot Tub": "Oia",
  "Rodakas Hotel": "Akrotiri",
  "VILLAKI 1": "Oia",
  "Villa Basilica Tefsia": "Emporio",
  "Alaso Design Suites": "Fira",
  "Αφροδίτης": "Kamari",
  "Stavros Villas": "Karterados",
  "Core Of Fira Apartments": "Fira",
  "SEA HEAVEN CAVE": "Oia",
  "Alaya Suites": "Pyrgos",
  "Fanari vista suites": "Fira",
  "Red Beach Harmony suites Modestos": "Akrotiri",
  "ARTEMIS SUITES": "Megalochori",
  "Kasimatis by La Perla": "Imerovigli",
  "Seaside Breeze": "Kamari",
  "Armenaki": "Oia",
  "Casa paradiso private villas": "Oia",
  "Suites of the Gods Cave Spa Hotel": "Megalochori",
  "Mirabo Villas": "Firostefani",
  "Zannos Melathron Hotel by Omilos Hotels": "Pyrgos",
  "Sigal Villa": "Akrotiri",
  "Blue Sapphire Hotel": "Perissa",
  "Aspaki by Art Maisons": "Oia",
  "Cavo Bianco": "Kamari",
  "Arotron Santorini": "Pyrgos",
  "Virginia's Cave Villas": "Oia",
  "Pantelia Suites": "Fira",
  "La Roka": "Imerovigli",
  "Christina Pension": "Karterados",
  "Casa Bella": "Kamari",
  "SantoriniNY": "Perissa",
  "Villa Fabrica Santorini": "Pyrgos",
  "Ipapantis": "Fira",
  "Seaside Breeze": "Kamari",
  "Sol Mare Salis": "Kamari",
  "Youth Hostel Anna": "Perissa",
  "Rodakas Hotel": "Akrotiri",
  "Ikaros Hotel": "Karterados",
  "Efippos": "Vlychada",
  "Nostos Apartments Kamari": "Kamari",
  "Joy Beach Ηotel": "Perivolos",
  "Santoimage house": "Oia",
  "Atrina Canava 1894": "Oia",
  "Morfes Luxury Suites by Caldera Houses": "Firostefani",
  "Twenty One Suites": "Oia",
  "Dolce Suites": "Kamari",
  "Kore Cave House by Oias Local Cave Houses": "Oia",
  "Asera Suites - Prive jacuzzi": "Kamari",
  "Beach Boutique Hotel": "Kamari",
  "Join Us Low Cost Rooms": "Kamari",
  "Stay Lux Suites": "Karterados",
  "Hermes Hotel": "Kamari",
  "Golden Moments Luxury Stone Villas B": "Messaria",
  "Apanomeria Boutique Residence": "Oia",
  "West East Suites": "Imerovigli",
  "Annouso Villa by Caldera Houses": "Oia",
  "Antinea Suites Hotel": "Kamari",
  "Luna Santorini Suites": "Pyrgos",
  "8FR4+Q6V Agios Georgios": "Perivolos",
  "Salida Del Sol Luxury suites Santorini": "Exo Gonia",
  "The Lighthouse Sunset View Suites": "Akrotiri",
  "Colombos Beachfront": "Koloumbo",
  "Pansion Zaharoula": "Fira",
  "Vedema": "Megalochori",
  "Blue Dream - Santorini": "Kamari",
  "Villa Maria Apartments": "Akrotiri",
  "Barolo Beach": "Perivolos",
  "Citizen Service Center": "Oia",
  "Α.Ο. Πανθηραϊκός": "Karterados",
  "Honeymoon Petra": "Imerovigli",
  "Belle Etoile Villas": "Imerovigli",
  "Georgia Pelekanou Studios": "Fira",
  "Enalion Houses": "Oia",
  "La Madeleine": "Oia",
  "SANTORINI GRAND LUXURY VILLAS": "Imerovigli",
  "Arany Terra": "Imerovigli",
  "Apeiron Blue Santorini by Apeiron Hotels": "Messaria",
  "Cilon Suites Santorini": "Imerovigli",
  "Omna Caldera Suites": "Akrotiri",
  "Village Anto Fira": "Fira",
  "Antoniou Santorini": "Fira",
  "Olvos Luxury Suites": "Oia",
  "Antonia Apartments": "Fira",
  "Maistros Village": "Karterados",
  "Notos Therme and Spa": "Vlychada",
  "Frati Villas Beachfront": "Perissa",
  "La Perla Villas and Suites - Adults Only": "Oia",
  "Yposkafo Suites - Villa - Santorini": "Fira",
  "Aelia by Eltheon": "Imerovigli",
  "Santozen Suites": "Fira",
  "White Haven Cave Home": "Messaria",
  "Belle Etoile Villas": "Imerovigli",
  "White Grape Suites": "Foinikia",
  "AETHRIO SUNSET VILLAGE. TRADITIONAL HOTEL. OIA": "Oia",
  "Inoe Boutique Hotel": "Kamari",
  "Bay View Residences Santorini": "Akrotiri",
  "Oia Waves Cave Houses": "Oia",
  "Almyra Oia Suites": "Oia",
  "9CPH 7P": "Port",
  "ALSAKI SUITE by K": "Oia",
  "Semprou Rooms": "Perissa",
  "Absolute Paradise Santorini": "Akrotiri",
  "Sandy Villas": "Emporio",
  "Dome Santorini Resort": "Imerovigli",
  "Caves 1880": "Foinikia",
  "Santorini Princess Presidential Suites": "Akrotiri",
  "Drossos Car Rental Tourist Office": "Oia",
  "Gorgona Villa": "Imerovigli",
  "Onar Villas Oia - Onar Hotels Collection": "Oia",
  "Shades of White Villas": "Emporio",
  "Stardust Suites": "Kamari",
  "Agiou Ioannou 356": "Fira",
  "Oinos Luxury Suites": "Foinikia",
  "The Noverian Bios Santorini": "Fira",
  "Aroma Azalea studios apartments - Studio with Sea View": "Kamari",
  "Cyclades Hotel": "Karterados",
  "San Marino Suites by Calm Collection": "Fira",
  "Floria Suites": "Karterados",
  "Cave House": "Imerovigli",
  "Fanouris Condo - Adults Only": "Kamari",
  "Archontiko Suites Santorini": "Fira",
  "Loucas on the Cliff": "Fira",
  "Amor Hideaway Villas by Mr and Mrs White": "Fira",
  "Aegean Nest Beach Studios - Adults only": "Monolithos",
  "Samson΄s Village": "Perissa",
  "Aroma Azalea studios apartments - Studio with Sea View": "Kamari",
  "Dreamland Houses": "Oia",
  "Maralex": "Fira",
  "Margarenia": "Perissa",
  "LUKAS Aethereal Living": "Imerovigli",
  "Dimitris Ammoudi Taverna": "Ammoudi",
  "Native Eco Villas": "Imerovigli",
  "Captain John Houses Oia Center": "Oia",
  "Santorini Hillside Suites": "Pyrgos",
  "3 Domes Viewpoint": "Oia",
  "Blue Art Caves": "Oia",
  "Thera Villas": "Fira",
  "ArcadOIA House": "Oia",
  "Ira Apartments": "Kamari",
  "Villa Mare Angelica": "Perivolos",
  "Aidani Luxurious Rooms": "Messaria",
  "Cliff Aura Suites": "Fira",
  "Villa Lukas": "Imerovigli",
  "Take a wok": "Kamari",
  "Èros suites Oia": "Oia",
  "Edem Rooms": "Fira",
  "Canyon Santorini": "Fira",
  "Oinos Luxury Suites": "Foinikia",
  "Living Moments": "Messaria",
  "Villa Angira": "Kamari",
  "Nikolas Villas": "Perivolos",
  "Maralex": "Fira",
  "Black Coast Santorini": "Perivolos",
  "Caldera Butterfly Villas": "Messaria",
  "Avelora Suites": "Pyrgos",
};

export function normalizeHotel(value, reference) {
  if (!value) return "";
  const name = value.split(",")[0].trim();
  
  if (HOTEL_MAP[name] !== undefined) return HOTEL_MAP[name];

  console.warn("Unknown hotel, add to HOTEL_MAP:", name);
  
  const afterFirstComma = value.split(",").slice(1).join(",").trim();
  const locationGuess = normalizeLocation(afterFirstComma);
  if (locationGuess !== afterFirstComma) return locationGuess;

  return `TBA`;
}
