import { normalizeLocation } from "./locations.js";

export const HOTEL_MAP = {
  "Hillside Elegance": "Oia",
  "Kamari Blue Boutique Hotel": "Kamari",
  "Belvedere Suites": "Firostefani",
  "bus station Fira": "Fira",
  "Callia Retreat Suites - Adults Only": "Fira",
  "Akrotiri Castle View": "Akrotiri",
  "Akrotiri Hidden Gem": "Akrotiri",
  "Avant Garde Firostefani": "Firostefani",
  "Avant Garde": "Akrotiri",
  "Santo Wines": "Pyrgos",
  "Andronikos Santorini Hotel": "Imerovigli",
  "Olympic Villas": "Oia",
  "Ocean Bay Suites": "Kamari",
  "Unique Suites": "Imerovigli",
  "Radisson Blu Zaffron Resort": "Kamari",
  "Cresanto Luxury Suites": "Imerovigli",
  "Remezzo Villas": "Imerovigli",
  "Santo Miramare Beach Resort": "Perivolos",
  "Potamida Suites": "Fira",
  "Sail Inn Studios": "Kamari",
  "Agnadema Apartments": "Fira",
  "Chez Sophie": "Kamari",
  "Ifestos Villa": "Fira",
  "Echoes Luxury Suites": "Oia",
  "Elite Luxury Suites": "Oia",
  "Loizos Stylish Residences": "Fira",
  "WHITE": "Kamari",
  "Hotel Santorini": "Fira",
  "Blue Canaves Boutique Villa": "Oia",
  "Acropole Sunrise": "Kamari",
  "Cultural House": "Pyrgos",
  "Maria's Place - Adults Only": "Oia",
  "Petit Palace Suites": "Messaria",
  "Kamari Santorini": "Kamari",
  "Gyros Place": "Perissa",
  "Sunray Lodgings": "Kamari",
  "Central Bus Station Fira": "Fira",
  "Santolia Art Suites": "Oia",
  "Vogue Suites": "Oia",
  "Lotza Studios": "Foinikia",
  "North Wind Luxury Suites": "Oia",
  "Anemomilos": "Oia",
  "Santonero": "Akrotiri",
  "Black Occhio Villa": "Karterados",
  "Ikaros": "Karterados",
  "White Ark": "Fira",
  "Santo Mangata Boutique Hotel": "Perissa",
  "Langas Villas": "Imerovigli",
  "Hotel Acropole Sunrise": "Kamari",
  "Onar Rooms": "Perissa",
  "Caldera Premium Villas": "Oia",
  "Amaryllis Suites Santorini": "Fira",
  "Sea Sound White Katikies": "Perivolos",
  "Secret Gem Suites": "Ammoudi",
  "Amphitheater Cave Houses": "Fira",
  "Anemos View": "Fira",
  "Hotel Porto Perissa": "Perissa",
  "Ambeli Apartments": "Perivolos",
  "Unique Galini Oia - Adults Only": "Oia",
  "Iconic Santorini": "Imerovigli",
  "Transfer service": "Kamari",
  "Costa Grand Santorini": "Kamari",
  "Andromeda Villas": "Imerovigli",
  "Amity Suites - Adults Only": "Fira",
  "Altana Heritage Suites": "Imerovigli",
  "Hippocampus Hotel": "Kamari",
  "VIP Santorini Transfers and Tours": "Oia",
  "Marizan Caves": "Oia",
  "Chelidonia Luxury Suites": "Oia",
  "Finikas Hotel": "Kamari",
  "Charisma Suites": "Oia",
  "Joanna Villas": "Kamari",
  "Levante Beach Hotel": "Kamari",
  "Thiras-Oias": "Oia",
  "Kamares Apartments": "Fira",
  "Vlyhada Μarina": "Vlychada",
  "Athiri Luxury Suites": "Perivolos",
  "Captain John Oia Cave Houses - Sunset": "Oia",
  "Ianthe Apartments": "Oia",
  "Antonia Hotel": "Fira",
  "Santorini Heart - Hotel": "Fira",
  "Luxus VIP Suites": "Oia",
  "Marianna Hotel": "Perissa",
  "Golden Star": "Fira",
  "Avocado": "Imerovigli",
  "Órmos Athiniós": "Port",
  "Perla Nera Suites": "Fira",
  "Villa Solasta": "Akrotiri",
  "Cliff Side Suites": "Firostefani",
  "Villa Rose": "Fira",
  "Afroditi Venus Beach Resort": "Kamari",
  "Agali Houses": "Firostefani",
  "Sunborn Oia Suites": "Foinikia",
  "Voodoo Bar Santorini": "Kamari",
  "The Majestic Hotel": "Fira",
  "Filira Suites": "Perissa",
  "Kamarela Studios": "Kamari",
  "Epar.Od. Firon-Ias": "Foinikia",
  "MAR n MAR CROWN HOTEL-SUITES": "Kamari",
  "Meltemi Village Hotel": "Perissa",
  "Floralia": "Karterados",
  "Hotel Sunshine": "Kamari",
  "Nostos Beach": "Kamari",
  "RK Beach Hotel": "Kamari",
  "Athinios port": "Port",
  "Kaliya Reimagined Food": "Fira",
  "Nova Santorini Luxury Suites": "Pyrgos",
  "Epar.Od. Firon-Ias 260": "Oia",
  "Afroditi Venus Beach Hotel": "Kamari",
  "OUTOPOIA CAVE STUDIOS": "Oia",
  "Dreamland Ηouses": "Oia",
  "Hotel Mohitero": "Kamari",
  "Vitsentzos Suites": "Imerovigli",
  "Moonlight Apartments": "Fira",
  "Terra Verde Oia by K": "Oia",
  "Hafen Santorin": "Port",
  "Santorini Palace": "Fira",
  "Viva Nove Suites": "Kamari",
  "Neo Suites": "Fira",
  "Alyvia Suites": "Oia",
  "Villa Koronios": "Fira",
  "Ira Hotel": "Fira",
  "Bellonias Villas": "Kamari",
  "Zoe Aegeas Traditional houses": "Oia",
  "Sandy's Paradise- Adults Only": "Perissa",
  "Hector Cave House": "Oia",
  "Fira Basement Studios": "Fira",
  "Kalestesia Suites": "Akrotiri",
  "Orizontes Hotel Santorini": "Pyrgos",
  "Cocoon Suites": "Imerovigli",
  "Orama Hotel": "Fira",
  "Limestone": "Fira",
  "Makedonias 5": "Kamari",
  "San Giorgio": "Fira",
  "Caldera Cliff Illusion": "Fira",
  "Santo Mine Oia Suites": "Oia",
  "Studio Mary": "Perissa",
  "Delta Suites": "Oia",
  "Filomare Oia Suites": "Oia",
  "Oia Spirit Boutique Residences": "Oia",
  "Enalion Suites": "Oia",
  "Sun Rocks Boutique Hotel - Caldera View Suites": "Fira",
  "Oia": "Oia",
  "Santorini Port": "Port",
  "Aegean Gold": "Kamari",
  "Hotel Thira": "Fira",
  "Santa Magia": "Kamari",
  "Alta Vista Suites": "Firostefani",
  "Splendour Hotel and Suites": "Firostefani",
  "Blu Rooms Santorini": "Akrotiri",
  "Aqua Luxury Suites by NOMÉE Hospitality Group": "Imerovigli",
  "Cycladic Suites": "Fira",
  "White Pearl Villas": "Oia",
  "Ananda Suites": "Imerovigli",
  "Villa Livadaros": "Karterados",
  "Divelia Hotel": "Perissa",
  "Epar.Od. Mesarias-Archeas Thiras": "Kamari",
  "Meltemi Excelsior Suites": "Perissa",
  "Santorini Rooftop Hot Tub Suite with Panoramic Views": "Akrotiri",
  "Spiliotica Central Apartments": "Fira",
  "Maistrali Prive": "Karterados",
  "Astarte Suites": "Akrotiri",
  "MiCasa": "Oia",
  "El Greco Resort": "Fira",
  "Platia": "Fira",
  "Filomare Suites": "Oia",
  "Fira": "Fira",
  "Dana Villas": "Fira",
  "La Mer Deluxe Hotel": "Fira",
  "Adorno Oia": "Oia",
  "Tzekos Villas": "Fira",
  "Three Domes Oia - an Iconic Collection": "Oia",
  "Altemar Suites": "Fira",
  "Aldea": "Karterados",
  "Adamant Suites": "Fira",
  "Apricus": "Perissa",
  "Kavalari Hotel - Adults Only": "Fira",
  "Villa Dima - Boutique Hotel": "Perissa",
  "Anemoessa Villa": "Oia",
  "Ethos Vegan Suites Fira": "Fira",
  "Galaxy Suites": "Imerovigli",
  "Christos Apartments Oia": "Oia",
  "Alexandros mini suites": "Perissa",
  "Aria Lito Mansion": "Fira",
  "Fira Sunrise and Sea View Cave": "Fira",
  "Chelidonia Traditional Villas": "Oia",
  "Artemis Village": "Karterados",
  "Nikki Beach Resort": "Monolithos",
  "Santorini Old Harbor": "Old Port",
  "Anila Suites": "Fira",
  "La Perla Villas and Suites": "Oia",
  "Mandilaria Studios": "Emporio",
  "Hidden Hills": "Messaria",
  "Muses Cycladic Suites": "Oia",
  "Villa Ilios": "Karterados",
  "Olive Leaf Houses": "Firostefani",
  "3 Elements by Stylish Stays": "Oia",
  "Pension George": "Karterados",
  "Canaves Oia Suites": "Oia",
  "Lefkothea Hotel": "Kamari",
  "my life suites": "Fira",
  "Villa Pelekanos": "Karterados",
  "Kýma Perissa": "Perissa",
  "Kalisperis Hotel": "Messaria",
  "Santorini View Hotel": "Akrotiri",
  "Villa Agas": "Karterados",
  "Sweet Pop": "Fira",
  "Santorini Crystal Blue Boutique Hotel": "Kamari",
  "San Antonio - Small Luxury Hotels of the World": "Imerovigli",
  "Alexander's Suites": "Oia",
  "Alesahne Beach Hotel": "Fira",
  "Nano Suites": "Exo Gonia",
  "Maregio Suites": "Oia",
  "Makris Beach Hotel": "Kamari",
  "Villa Eleftheria": "Perivolos",
  "Ferry entre Atenas y Santorini": "Port",
  "Adorno Oia Suites": "Oia",
  "Anatoli Hotel": "Fira",
  "Anastasia Princess Luxury Beach Residence": "Perissa",
  "Mon Signor Adults Only Boutique Hotel - Kamari Santorini": "Kamari",
  "Veggera Hotel": "Perissa",
  "Villa Maria Rooms": "Fira",
  "Makedonias": "Kamari",
  "Aperanto Suites": "Foinikia",
  "Lava Stone": "Ammoudi",
  "3 Caves by Caldera Houses": "Oia",
  "Thira Santorini Port": "Port",
  "Villa Konstantinos": "Perissa",
  "Marcos Rooms": "Oia",
  "Main Street": "Perissa",
  "Aressana Spa Hotel and Suites": "Fira",
  "Nectarios Villa - Studios": "Fira",
  "Blue Dolphins Santorini": "Firostefani",
  "Narkissos Hotel": "Kamari",
  "CAPE 9 Villas": "Akrotiri",
  "The Boathouse Hotel": "Kamari",
  "Mythos": "Pyrgos",
  "SantoNight Luxury Villas": "Messaria",
  "Blue Sea Hotel": "Kamari",
  "Agiou Athanasiou 69": "Fira",
  "Villa Fotini": "Firostefani",
  "Plastiras Rooms": "Fira",
  "Cave Suite Oia": "Oia",
  "Mystique": "Oia",
  "Alexandra Hotel": "Kamari",
  "Proteas Hotel": "Kamari",
  "Holy Cathedral of Saint John the Baptist": "Fira",
  "Apikia Santorini": "Pyrgos",
  "Pelican Hotel": "Fira",
  "Amaya Selection of Villas": "Oia",
  "Aethrio Sunset Village - Oia": "Oia",
  "Grand View - Megalochori Santorini": "Megalochori",
  "The Amethyst Exclusive Suites Oia": "Oia",
  "Tholos Resort": "Imerovigli",
  "Nik. Nomikou": "Oia",
  "Santellini Hotel": "Kamari",
  "ALMA THERA Boutique Hotel": "Perissa",
  "Port de Santorin": "Port",
  "25is Martiou 25": "Fira",
  "Stella Rocca A Mare": "Imerovigli",
  "You and Me Suites Oia": "Oia",
  "Lefteris Traditional Rooms": "Fira",
  "Casa Grande Santorini": "Megalochori",
  "Sun Angelos Oia - Luxury Cave Suites": "Oia",
  "Altemar Suites Santorini": "Fira",
  "Aeon Suites - Adults Only": "Pyrgos",
  "Smaragdi": "Perissa",
  "Santorini Cable Car - Upper Station": "Fira",
  "Fira Deep Blue Suites": "Fira",
  "Santorini Main Square": "Fira",
  "Fanari Vista Suites": "Fira",
  "Rivari Santorini Hotel": "Kamari",
  "Hotel Mylos": "Firostefani",
  "Bus Stop to Fira": "Fira",
  "Volkan on the Rocks": "Firostefani",
  "Smart Fira Stay -Designed Suites": "Fira",
  "Costa Grand Resort": "Kamari",
  "Iliovasilema Suites": "Imerovigli",
  "Villaki Oia": "Oia",
  "Panorama Boutique Hotel": "Fira",
  "Penelope's Ouzeri Pyrgos Santorini": "Pyrgos",
  "Petra Nera": "Perissa",
  "Sky of Thira": "Fira",
  "Caval I": "Fira",
  "Uma Ray Suites": "Fira",
  "Keti Hotel": "Fira",
  "Perissa BeachFront Rooms": "Perissa",
  "Katikies Santorini - Pelagos House - The Leading Hotels Of The World": "Oia",
  "Santorini Mesotopos": "Messaria",
  "Gianna Suites": "Fira",
  "Karidis Hotel": "Kamari",
  "Imerovigli": "Imerovigli",
  "Ptolemeos Hotel": "Fira",
  "Gaia Suites": "Oia",
  "Istoria": "Perissa",
  "Abelonas Village": "Megalochori",
  "Kasimatis by La Perla - Adults Only": "Imerovigli",
  "Finikia Memories Hotel (Finikia's Place)": "Foinikia",
  "Nissia Apartments": "Kamari",
  "Manos Small World": "Fira",
  "Mardanza Krokos Suites": "Imerovigli",
  "Daydream Luxury Suites": "Fira",
  "Hotel Leta": "Fira",
  "Akrorama Villa and Suites": "Akrotiri",
  "Grand View Hotel": "Megalochori",
  "Arapiou Apartments": "Perissa",
  "Kima Oia Suites": "Oia",
  "The Nest Apartments": "Fira",
  "Pano Meria Venetian Style Studio I": "Oia",
  "Santorini Kastelli Resort": "Kamari",
  "Selini Ηotel": "Kamari",
  "Santo Pure Oia Suites": "Oia",
  "Terra Blue Santorini": "Kamari",
  "Anastasia Princess Luxury Beach Residence - Adults Only": "Perissa",
  "Villa Thiranthemis": "Fira",
  "Santo Blue Horizon - The Blue Domes View": "Oia",
  "Hotel Lodos": "Karterados",
  "Chic Hotel Santorini": "Firostefani",
  "Sandy's Paradise Infinity Resort": "Perissa",
  "Vinas Place City Center": "Fira",
  "Anemomilos Hotel Apartments Villas": "Oia",
  "Altera Pars Suites": "Messaria",
  "Philippion Boutique Hotel": "Fira",
  "Amerikanos Villas": "Oia",
  "Anessis": "Fira",
  "Kalisti Hotel & Suites": "Fira",
  "Oia Steps": "Ammoudi",
  "Lackos Luxury Suites": "Vourvoulos",
  "Arlene Suites": "Messaria",
  "Panorama Oia Apartments": "Foinikia",
  "Hotel Golden Star": "Fira",
  "Santorini Heart Hotel": "Fira",
  "The Museum Project Oia": "Oia",
  "Folia Apartments": "Fira",
  "The Vasilicos": "Imerovigli",
  "Fira Heart Studios": "Fira",
  "Ducato di Oia - Adults Only": "Oia",
  "Santorini Theasis Suites": "Imerovigli",
  "Delfini Villas": "Oia",
  "Hotel Perissa": "Emporio",
  "Cally Cave House": "Fira",
  "Aressana Spa Hotel": "Fira",
  "Absolute Bliss": "Imerovigli",
  "Aegean Plaza Hotel": "Kamari",
  "Meroviglia Boutique Hotel": "Imerovigli",
  "Meltemi Village": "Perissa",
  "Dioskouri Art Villas": "Kamari",
  "Tholaki luxury home": "Kamari",
  "Bluedome Cavehouses by Otium Villas": "Oia",
  "Kamari Beach Hotel": "Kamari",
  "Ilioperato Hotel": "Imerovigli",
  "Afroessa Hotel by Caldera Houses": "Imerovigli",
  "Oia Mare Villas": "Oia",
  "Caldera's Bliss Suites": "Fira",
  "Aqua Blue Beach Hotel": "Perissa",
  "Impressive One Hotel": "Fira",
  "King's Suites": "Kamari",
  "Alleys All-Suite Hotel": "Pyrgos",
  "Regina Mare-Adults Only Hotel": "Imerovigli",
  "Cosmopolitan Suites - Small Luxury Hotels of the World": "Fira",
  "Senses Boutique Hotel": "Imerovigli",
  "Senses Suites": "Imerovigli",
  "Akis Hotel": "Kamari",
  "Alaxandross mini suites": "Perissa",
  "WeSense Santorini by Caldera Houses": "Imerovigli",
  "Megalochori": "Megalochori",
  "Iliovasilema Hotel": "Imerovigli",
  "Ark": "Pyrgos",
  "Skyfall Suites - Adults Only": "Pyrgos",
  "Meltemi Blu - Adults Only": "Perissa",
  "Cleo's Dream Villa": "Oia",
  "Petri Suites": "Perivolos",
  "Casa Frati Suites": "Perivolos",
  "Porto Fira Suites": "Fira",
  "Lilium Hotel Santorini": "Messaria",
  "Zephyros Hotel": "Kamari",
  "Nastram Suites Oia": "Oia",
  "Galatia Villas": "Fira",
  "Kapari Natural Resort": "Imerovigli",
  "Santorini Sun Villas": "Oia",
  "Perissa": "Perissa",
  "Valery Suites": "Fira",
  "Aura Marina Apartments Santorini": "Akrotiri",
  "Tiara Suites Fira - Cycladic": "Fira",
  "25is Martiou 405": "Fira",
  "Elysian Santorini": "Foinikia",
  "Elixir Del Mar on the Beach": "Kamari",
  "Mardanza House": "Imerovigli",
  "Blue Sea": "Kamari",
  "HIDEAWAY CAVE HOUSE": "Oia",
  "Agnadi View Villa": "Foinikia",
  "Kiklamino Sunset Suites": "Foinikia",
  "Bligos Villas": "Oia",
  "Glykeria Mini Suites": "Perivolos",
  "Asha Luxury Suites": "Fira",
  "SPIROS": "Perissa",
  "Divino Caldera": "Akrotiri",
  "Aeolos Art": "Imerovigli",
  "White Element": "Messaria",
  "Theodora Suites": "Oia",
  "Wisteria Apartments": "Karterados",
  "Mitropoleos": "Fira",
  "Theoxenia Caldera Hotel": "Fira",
  "Atrium Villa": "Fira",
  "Veranda View": "Imerovigli",
  "Sunflower ApartHotel": "Kamari",
  "Athermi Suites - Adults Only": "Megalochori",
  "Kykladonisia Traditional Settlement": "Fira",
  "Calypso Heaven": "Messaria",
  "Hotel Matina": "Kamari",
  "Unique Leta": "Fira",
  "Porto di Santorini": "Port",
  "Alkyon Hotel": "Kamari",
  "White Pearl Laokasti Suites": "Oia",
  "Asma Suites": "Fira",
  "Smaro Studios": "Firostefani",
  "Lolita's Gelato": "Oia",
  "Red Beach Viewpoint": "Akrotiri",
  "Strogili Hotel - Adults Only": "Kamari",
  "Picturesque Blue Dome Santorini": "Oia",
  "Church of the Holy Cross": "Perissa",
  "Sorocada Private House": "Akrotiri",
  "Corner Food": "Perissa",
  "Asimina Hotel": "Fira",
  "Pension Ptolemeos": "Fira",
  "Firostefani": "Firostefani",
  "Aroma Suites": "Fira",
  "BlackBeach Village": "Perissa",
  "Centro Fira": "Fira",
  "Hotel Thirasia": "Fira",
  "Erato Apartments": "Firostefani",
  "Kivotos Santorini": "Imerovigli",
  "Three Bells Suites": "Firostefani",
  "Nova Luxury Suites": "Pyrgos",
  "Fileria Suites": "Oia",
  "Opalia Suites": "Perissa",
  "NĒRO Suites by NOMÉE Hospitality Group": "Imerovigli",
  "Gabbiano Traditional Cave Houses": "Fira",
  "Aeolos Studios": "Imerovigli",
  "Astra Suites": "Imerovigli",
  "Mon Signor": "Kamari",
  "Lavadoze Luxury Suites": "Exo Gonia",
  "Dekigala 40c": "Fira",
  "Hotel Babis": "Karterados",
  "Blue Waves Suites": "Kamari",
  "Rocabella Santorini Hotel": "Imerovigli",
  "Monolithia": "Monolithos",
  "Kivotos Santorini - Preferred Hotels": "Imerovigli",
  "Canaves Oia Suites - Small Luxury Hotels of the World": "Oia",
  "Vallais Villa": "Imerovigli",
  "Thousand Stars Suites": "Kamari",
  "Villa Toula": "Fira",
  "Amer Suites": "Fira",
  "Katerina Kafieri Apartments": "Fira",
  "Aria Suites": "Fira",
  "Aura Suites": "Fira",
  "Perivolos Apartments": "Emporio",
  "Casa Sigala volcano": "Oia",
  "Sandblu Santorini": "Kamari",
  "Old Castle Oia": "Oia",
  "Sakas Residences": "Karterados",
  "Central Fira Suites": "Fira",
  "Anchor Suites": "Foinikia",
  "Thea Apartments": "Imerovigli",
  "Efippos-Santorini Riding Center": "Vlychada",
  "On the Cliff": "Fira",
  "IfestAu.4 Suites": "Fira",
  "City Center Suites": "Fira",
  "La Maltese Estate": "Imerovigli",
  "M Residence Santorini Conelia Cave": "Fira",
  "NĒRO Boutique Hotel": "Imerovigli",
  "Casa Sigala arch": "Oia",
  "Sole d'oro Luxury Suites": "Oia",
  "Asterolithos": "Fira",
  "Avianto Suites": "Imerovigli",
  "Hotel Hellas": "Fira",
  "Aroma Azalea studios": "Kamari",
  "Nostos Central Cave House with jacuzzi": "Fira",
  "Cuore Santo Suites": "Fira",
  "Hill Suites": "Fira",
  "May Seven Suites": "Megalochori",
  "White Harmony Suites": "Megalochori",
  "Roula Villa Studios": "Perissa",
  "Villa Anto": "Fira",
  "Heliophos Boutique Caves": "Foinikia",
  "Apollo Rooms": "Perissa",
  "hom Santorini": "Oia",
  "Anemomilos Villa": "Fira",
  "Veggera Beach Hotel": "Perissa",
  "Porto de Santorini": "Port",
  "Altea Apartments": "Fira",
  "Harmony Suites": "Fira",
  "Splendour Hotel": "Firostefani",
  "Santorini Camping": "Fira",
  "Hotel The Best": "Perissa",
  "Boutique 88 Fira": "Fira",
  "Nostos Apartments": "Oia",
  "Revelis Villa": "Fira",
  "Dilay Cafe Snack Bar": "Kamari",
  "Akra Suites": "Imerovigli",
  "Villa Manos Hotel": "Karterados",
  "Amera Suites": "Fira",
  "Deluxe Suites Santorini": "Fira",
  "Galini": "Foinikia",
  "Hyperion Oia Suites": "Oia",
  "Anteliz Suites": "Fira",
  "Aspaki Exclusive Hotel by Art Maisons": "Oia",
  "Stella Nomikou Apartments": "Fira",
  "Babis Hotel": "Karterados",
  "Dream Island Hotel": "Fira",
  "Sophia Luxury Suites": "Imerovigli",
  "Sweet Heart Studios": "Kamari",
  "HOTEL Dolphin": "Perissa",
  "Sophia Boutique Hotel": "Foinikia",
  "White Cellar cave houses by Cycladica": "Oia",
  "Pearl Inn Hotel by Pearl Hotel Collection": "Imerovigli",
  "City Break": "Fira",
  "Taverna El Greco": "Fira",
  "Castle of Oia": "Oia",
  "Coconut Residence": "Karterados",
  "Villa Thiranthemis Santorini": "Fira",
  "Brilliance Suites": "Imerovigli",
  "Villa Margarita": "Karterados",
  "Santopaz Suites": "Oia",
  "Kamares Neoklassiko": "Fira",
  "Aeifos Boutique Hotel": "Imerovigli",
  "Divino Suites": "Fira",
  "Aegean Blue Suites": "Pyrgos",
  "Sagma Beach Rooms": "Perissa",
  "Villa Kisiris": "Imerovigli",
  "haven van Santorini": "Port",
  "Notos Therme and Spa by Mr and Mrs White": "Vlychada",
  "Irene City Villas": "Fira",
  "Pura Vida Cave House": "Imerovigli",
  "KooKoo Bar Restaurant Sunset Rooftop": "Oia",
  "Finikia 847 02": "Foinikia",
  "SunUp Lux Villa": "Oia",
  "Villa Murano": "Fira",
  "Hom Santorini": "Oia",
  "Aelia Luxury Suites": "Karterados",
  "OIA UNIQUE HOMES by K": "Oia",
  "Marousi Rooms": "Perissa",
  "Agiou Athanasiou 39": "Fira",
  "Villa Happening": "Imerovigli",
  "Aghios Artemios Traditional Houses": "Imerovigli",
  "Golden Moments Luxury Stone Villas C": "Messaria",
  "Aspa Villas": "Oia",
  "Porto Castello": "Fira",
  "Markakis Studios Fira Town": "Fira",
  "Oia Parking": "Oia",
  "Afrodete Hotel": "Fira",
  "De Sol Hotel": "Fira",
  "Alloro Perissa": "Perissa",
  "Ikio Concept": "Pyrgos",
  "New Haroula": "Fira",
  "Artemis Suites": "Megalochori",
  "Sweet Home": "Karterados",
  "Heyday Luxury Suites": "Perissa",
  "Rooms By Lignou": "Fira",
  "Elessa Hotel": "Pyrgos",
  "Ambience Suites": "Fira",
  "Agave Santorini Design Βoutique Hotel": "Imerovigli",
  "Nefeli Homes - Adults Only": "Imerovigli",
  "The lemon tree studio": "Fira",
  "Cooper's Cave house with heated Jacuzzi": "Megalochori",
  "Casa Sigala sunset": "Oia",
  "Ikio Concept Santorini": "Pyrgos",
  "Caldera Romantica Hotel": "Akrotiri",
  "Aigialos Luxury Traditional Settlement": "Fira",
  "Hotel Kallisto": "Imerovigli",
  "The Arches": "Oia",
  "Reverie Santorini Hotel": "Firostefani",
  "Mythical Blue Luxury Suites": "Fira",
  "Kalimera Hotel": "Akrotiri",
  "Fanari Villas": "Oia",
  "North Santorini - A Luxury Spa Hotel": "Pyrgos",
  "Little Rock Villa - Oia": "Oia",
  "Old Castle Oia by Mr and Mrs White": "Oia",
  "Santa Mar ECO Suites": "Karterados",
  "Fira Cozy Rooms": "Fira",
  "Alonia Studios": "Firostefani",
  "Oscar Hotel": "Kamari",
  "Caval II": "Fira",
  "La Torretta Suites": "Pyrgos",
  "Villa Soula": "Fira",
  "Nefeles Luxury Suites": "Fira",
  "Amerisa Suites": "Fira",
  "Orthodox Metropolitan Cathedral": "Fira",
  "Kamari Beach": "Kamari",
  "Epavlis Hotel": "Kamari",
  "Hotiday Santorini Oia": "Foinikia",
  "Enarma Suites": "Megalochori",
  "Oia Treasures Art Suites": "Oia",
  "Maiandros Suites": "Karterados",
  "Diamond on the cliff Hotel": "Imerovigli",
  "Myst Boutique Hotel": "Oia",
  "Volcano View Hotel Santorini": "Fira",
  "Safrani Suites": "Fira",
  "Safrani Suites": "Fira",
  "June Twenty Suites": "Messaria",
  "La Bellezza Eco Boutique Hotel": "Kamari",
  "Acqua Vatos Santorini Hotel": "Kamari",
  "Fira Deep Blue Suites": "Fira",
  "Abasa Suites": "Fira",
  "Athina Luxury Suites": "Fira",
  "Villa Maina": "Kamari",
  "Pink Sophia Maria": "Imerovigli",
  "White": "Imerovigli",
  "Aja Retreat Luxury Suites": "Kamari",
  "Ifestia Hotel": "Kamari",
  "Onyx Hotel": "Karterados",
  "Vallas Apartments": "Firostefani",
  "PERIVOLAS MARKET": "Oia",
  "Elea Resort - Adults Only": "Oia",
  "Anthonas Apartments": "Imerovigli", 
  "Evgenia Villas": "Fira",
  "Voca Hotel": "Kamari",
  "Kastro Suites": "Fira",
  "Marillia Village": "Perivolos",
  "Hotel Bella Santorini": "Perivolos",
  "Smarula Villa": "Firostefani",
  "IKIES Santorini": "Oia",
  "Pezoules of Oia": "Oia",
  "Orabel Suites Santorini (Adults Only)": "Perivolos",
  "Villa Amore": "Karterados",
  "OPALIA SUITES": "Perissa",
  "Canaves Ena - Small Luxury Hotels of the World": "Oia",
  "Atlantis Beach Villa": "Perivolos",
  "MIA'S RESTAURANT SANTORINI": "Oia",
  "Serenità Luxury Suites": "Akrotiri",
  "Palm Studios": "Perissa",
  "Chroma Suites": "Oia",
  "Alizea Villas": "Fira",
  "Emfasis Luxury Villa with heated Jacuzzi-Sunset view": "Fira",
  "Seaside by Manos": "Kamari",
  "Dioskouri art Villas": "Kamari",
  "Olia Villas": "Imerovigli",
  "Petros Villa": "Fira",
  "Spitia Santorini Villa Collection": "Oia",
  "Oasis Suites Fira": "Fira",
  "Rose Bay Hotel": "Kamari",
  "Fanari Villas Santorini": "Oia",
  "MG Boutique Hotel": "Perissa",
  "Oia VineyART Homes": "Oia",
  "Nevma Suites": "Firostefani",
  "Callia Retreat Suites": "Fira",
  "Kasteli Luxury Rooms": "Perissa",
  "Thirea Suites": "Oia",
  "Evilio Houses": "Oia",
  "Santorini Villatzio Suites": "Messaria",
  "Astir Thira Hotel": "Fira",
  "Amelot Art Suites": "Fira",
  "Iriana Suites": "Fira",
  "Griseo Villas": "Karterados",
  "McDonald's Σαντορίνη": "Fira",
  "Black Diamond Suites": "Akrotiri",
  "Apeiron Blue Santorini - Sustainable Adults Only 14 Plus": "Fira",
  "Kalya Suites": "Kamari",
  "Nissos Thira Hotel": "Fira",
  "Santa Elena": "Kamari",
  "Maison Dalidaz": "Messaria",
  "Nissia Beach Apartments": "Kamari",
  "Blue Bay Villas": "Kamari",
  "Villa Valvis": "Perissa",
  "Allure Breeze Suites": "Oia",
};

export function normalizeHotel(value, reference) {
  if (!value) return "";
  const name = value.split(",")[0].trim();
  
  if (HOTEL_MAP[name] !== undefined) return HOTEL_MAP[name];

  console.warn("Unknown hotel, add to HOTEL_MAP:", name);
  
  const afterFirstComma = value.split(",").slice(1).join(",").trim();
  const locationGuess = normalizeLocation(afterFirstComma);
  if (locationGuess !== afterFirstComma) return locationGuess;

  return `TBA`;
}